### ISSUE TITLE
Site: Cast Screws incorrect iron requirement

### ISSUE THREAD

**Issue by GrandaddypurpleK** [Maelstromeous/satisfactory-factories#3]
The tool says 50 screws/min require 250 iron ingots per minute, instead of 12,5 (so it's *20 more)

**Comment by Maelstromeous** [comment]
Related #1 

Game data shows:

- 12.5/m Iron Ingot
- Produces 50/m Screws

Looks like a math issue related to #1 where if a product is >1 requirements skyrocket.

**Comment by Maelstromeous** [comment]
Additional details:

My input was : 15 Heavy Modular Frame/min with the Heavy Flexible Frame recipe

-> 1560 screws required

-> showed me 7800 iron ingots per minute, while it should be 390

**Comment by GrandaddypurpleK** [comment]
It seems for some items, the required throughput is multiplied by the number of items produced by one cycle:
-Cast screw produces 20 screws, shown throughput requirement is *20 more than it should be
-Fused Quickwire produces 12 quickwire, shown requirement is *12 more than it should be

**Comment by Maelstromeous** [comment]
Yeah I believe it's the fact I times the quantity by the product requirements, which is the incorrect way it seems (clearly in my testing I didn't bother to look at other recipes that produce more than 1 item per production run).

My suspicion is it's this line: https://github.com/Maelstromeous/satisfactory-factories/blob/main/web/src/utils/factory-management/products.ts#L68C1-L68C68, which is flat multiplying the ingredient amount by the requested items per minute, which it should be doing a ratio of it using the recipe.

**Comment by Maelstromeous** [comment]
@GrandaddypurpleK This should now be fixed by https://github.com/Maelstromeous/satisfactory-factories/commit/63c083b2c91be73066bf3e700a90f464cd4254f5, could you give it another test? This should hopefully fix fluids as well. #2

**Comment by Maelstromeous** [comment]
Note you may need to "jiggle" your amounts to make the calculation apply

**Comment by GrandaddypurpleK** [comment]
> @GrandaddypurpleK This should now be fixed by [63c083b](https://github.com/Maelstromeous/satisfactory-factories/commit/63c083b2c91be73066bf3e700a90f464cd4254f5), could you give it another test? This should hopefully fix fluids as well. #2

Yep, the amounts are fixed for these recipes! I'll do some more testing later on

**Comment by Maelstromeous** [comment]
Awesome! I'll close this for now then, feel free to re-open if you spot something else!

**Comment by Maelstromeous** [comment]
Related: #4 #1
