### ISSUE TITLE
Site: Iron Plate recipe calculates at 3x and not 1.5x

### ISSUE THREAD

**Issue by gus** [Maelstromeous/satisfactory-factories#4]
The basic recipe for `Iron Plate` is calculating at 3x instead of 1.5x. What I expect to see if producing `20` iron plates with the non-alt Iron Plate recipe is that I need to provide `30` iron ingots. Currently, I'm told I need `60` iron ingots. Screenshot for good measure:

![image](https://github.com/user-attachments/assets/73673269-609d-4b7e-adba-9bf9032aecc0)

**Comment by Maelstromeous** [comment]
This should have been fixed in https://github.com/Maelstromeous/satisfactory-factories/commit/63c083b2c91be73066bf3e700a90f464cd4254f5, here's what it shows now:

![Screenshot 2024-11-16 at 15 00 22](https://github.com/user-attachments/assets/a5a8d4a9-c5da-4cf6-b6f7-5817f27d50b1)

**Comment by gus** [comment]
It is indeed fixed. Thank you!

Was almost in that `.ts` file looking to see if I could find what needed changing; but you clearly beat me to it :)
