### ISSUE TITLE
CI: Build the application as a status check

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstromeous/satisfactory-factories#47]
Deployments fail with Vercel but unfortunately without access to Vercel (which costs me $20 a seat!) collaborators are unaware of any issues. 

Need to add a workflow ran on PR to build the application and then status checks will report build errors to the collaborator.

**Comment by samsmithnz** [comment]
I'm not familiar with Vercel. What does that give us? Why not use [GitHub Actions deployment approvals](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/reviewing-deployments)? Most of the features are free for open source projects like this.

**Comment by Maelstromeous** [comment]
So Vercel is the host of the site, and it offers a lot to us in terms of previews and content hosting. Normally I can get away with the hobby plan so it's effectively free very high quality webhosting for front end apps such as this one, and I absolutely love it. However due to the site's absolute explosion in popularity (we reached 4k viewers in the space of 12 hours!) I had to pay for the pro plan temporarily, I shouldn't have to do that next month.

I know you work for GitHub, so if GitHub offer any form of SaaS hosting solutions where I can bring my own domain name I'm all ears :)

**Comment by samsmithnz** [comment]
GitHub does not offer hosting unfortunately - GitHub itself is relies on a combination of Azure, AWS, and its own data centers. 

I personally use a combination of Azure, Wordpress, and GoDaddy for my sites, none of those are free either. 

Let's monitor the usage over the next few months. There are options we could use to host this given it's all/mostly JavaScript.

**Comment by Maelstromeous** [comment]
If all fails I can self host it (like the backend already is), but Vercel's preview system is already amazing and it's a turn-key solution, I didn't have to do a thing to configure it, and it's GH integration is excellent. It's likely we can operate on the hobby plan for some time anyways, for free.
