### ISSUE TITLE
Add debug mode 

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstromeous/satisfactory-factories#50]
Need the ability to add a debug mode for easy development and collaboration.

Ideally, simply supplying <siteurl>?debug=true in the URL should do the trick. This should then show buttons on the bottom of each factory to debug it's data in a graphical format without having to go to the local storage, pull out the JSON into your IDE, format it blah blah upon every change.

Ideally if the URL is not the website URL it should show this by default, removing the need to add a query string.

**Comment by nils-keller-dev** [comment]
What exactly do you mean by "graphical format"? Should the child nodes be collapsible and expandable?

**Comment by Maelstromeous** [comment]
No, merely just a JSON print so SF developers can see data problems. 

The Graph view is intended to be the "visual" component to the planner. But, it's heavily WIP.
