### ISSUE TITLE
Did you add repository rules? I can't push to a new branch anymore

### ISSUE THREAD

**Issue by samsmithnz** [Maelstromeous/satisfactory-factories#67]
Getting the odd error: `Repository rule violations found Changes must be made through a pull request. - https://docs.github.com/rest/git/refs#update-a-reference`

**Comment by Maelstromeous** [comment]
@samsmithnz Should be fixed now, it appears as well I can tell copilot to review PRs, so I've turned that on 🤓

**Comment by samsmithnz** [comment]
And that is exactly what I was trying to do - asking Copilot to fix the power string issue for me... ;)

**Comment by samsmithnz** [comment]
That did the [trick](#68), I can open PR's again!
