### ISSUE TITLE
Certain Recipes / Products are missing

### ISSUE THREAD

**Issue by NotAtec** [Maelstromeous/satisfactory-factories#8]
Haven't looked into it further, but trying to plan out my defense factory I noticed that the Nobelisk family of items (including Nuke & Cluster) are missing. Not sure if other items are too, but those are for certain.

They can be made in assemblers, so seems nice to have those recipes in the project too.

**Comment by Maelstromeous** [comment]
Yeah, I made the concious choice to remove any items that can be produced within the workbench and crafting bench. I'll consider dialing it back a bit so if an item is also made an assembler it should show up. I had to do a ton of filtering on the game data as it brought in a LOT of recipes (every single buildable is a recipe too).

Interestingly though Nobelisks appear to be most affected, Shattered Rebar for example shows up. If there's any others you spot please let me know.

**Comment by NotAtec** [comment]
Will do if i spot anything else.

Was just by chance that i spotted it either way, the "I want this to not be here anymore" factory is what was on my to do list next.

**Comment by Maelstromeous** [comment]
I've spotted the issue, it's when an item can be made in multiple buildings that the only the first building is being checked if it's made in just a workshop, fix should be coming shortly.

**Comment by Maelstromeous** [comment]
<img width="1074" alt="Screenshot 2024-11-16 at 18 46 15" src="https://github.com/user-attachments/assets/770ba63d-3423-4a7a-af9e-14e5ea67e343">

Nobelisks and various FICSMAS fireworks are now selectable. Thanks for reporting!
