### ISSUE TITLE
Same Products are not counted in the Satisfaction

### ISSUE THREAD

**Issue by Vladyslav25** [Maelstromeous/satisfactory-factories#9]
Hey. I have a factory with the same production (fuel). Using diffrent Alt Recepies. 
But down in the satisfaction only one of them is used.

![image](https://github.com/user-attachments/assets/7a92a60d-d370-454b-bf16-f7a907be32b0)
![image](https://github.com/user-attachments/assets/b255339e-ebde-428e-9029-9b459afb60b8)

**Comment by Maelstromeous** [comment]
Ah yes this is an issue that's on the big todo list, at the moment you currently can't enter in the same product twice on different recipies, the last one overrides it. I need to make it addative.

**Comment by Maelstromeous** [comment]
Marked as top priority fix. Should be done tonight or tomorrow.

**Comment by Maelstromeous** [comment]
Hello @Vladyslav25 , this has now been fixed! Please feed back if it is indeed fixed for you, if not please reopen.
